name: Website
description: Publish a PR if it has a specific label
inputs:
  java-distribution:
    description: JDK vendor (zulu, temurin, etc.)
    default: zulu
  java-version:
    description: Java version to setup (25)
    default: "25"
  memory-limit:
    description: Memory limit for sbt (2048 MB)
    default: "2048"
  cache-key:
    description: Cache key
    default: target
  command:
    description: Website command to run
    default: website
  site-path:
    description: Path to the site
    default: target/site

runs:
  using: "composite"
  
  steps:
   - name: Website Build
     uses: /WorldOfScala/actions/website@master
     with:
        java-distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        memory-limit: ${{ inputs.memory-limit }}
        cache-key: ${{ inputs.cache-key }}
        command: ${{ inputs.command }}
   - name: Setup Pages
     uses: actions/configure-pages@v6
   - name: Upload artifact
     uses: actions/upload-pages-artifact@v4
     with:
        path: ${{ inputs.site-path }}
   - name: Deploy to GitHub Pages
     
     id: deployment
     uses: actions/deploy-pages@v4


